ALTER TABLE "Plan" ADD COLUMN "productDiscountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "ticketDiscountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN "partnerDiscountPercent" INTEGER NOT NULL DEFAULT 0;
